[mongodb]
uri="mongodb+srv://jonpuray22_db_user:vOIpqVFz8wFlJXRI@cluster0.chellgi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

[my_email]
email="jonpuray@gmail.com"
pass="peux oxra nbpi jneq"