[mongodb]
uri="mongodb+srv://jonpuray22_db_user:vOIpqVFz8wFlJXRI@cluster0.chellgi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

[my_email]
email="no-reply@media-meter.com"
pass="PrSM6-wn"

[brevo]
api_key = "xkeysib-07s4cjCQZV1wUYd9"
from_email = "jonathan.puray@media-meter.com"
from_name = "Requests App"